user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /


main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /front

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
