<?php

namespace MainBundle\Repository;

/**
 * WebsiteDomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteDomaineRepository extends \Doctrine\ORM\EntityRepository
{
}
