<?php

namespace MainBundle\Repository;

/**
 * WebsiteDepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteDepartementRepository extends \Doctrine\ORM\EntityRepository
{
}
