<?php

namespace MainBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteActualiteRepository extends EntityRepository
{


 public function getLastActu(){

    $em=$this->getEntityManager();
    $query=$em->createQuery(
         'select a 
         from MainBundle:WebsiteActualite a 
         order by a.date desc' 

     	)->setMaxResults(1);

    return $query->getOneOrNullResult();

 }
 public function getAllByPage($firstRes,$maxRes=3){
       
    $em=$this->getEntityManager();
    
    $query=$em->createQuery(
         'select a
         from MainBundle:WebsiteActualite a
         order by a.date desc'
    	)->setFirstResult($firstRes)->setMaxResults($maxRes);

    return new Paginator($query,$fetchJoinCollection=true);


 }
 public function getFourLastActu(){

 	$em=$this->getEntityManager();

 	return $em->createQuery(
         'select a
         from MainBundle:WebsiteActualite a 
         order by a.date desc'
 		)->setMaxResults(4)->getResult();
 }


	
}
