<?php

namespace MainBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsitePoleRepository extends \Doctrine\ORM\EntityRepository
{

  public function getAll(){

    /*$em=$this->getEntityManager();
    $query=$em->createQuery('

           select p, img 
           from MainBundle:WebsitePole p, MainBundle:WebsiteImage img
           where p.id=img.pole_id

    	');

    return $query->getResult();*/
    

  }



	
}
