<?php

namespace MainBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteAgendaRepository extends \Doctrine\ORM\EntityRepository
{





	
}
