<?php

namespace MainBundle\Repository;

/**
 * WebsiteRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
