<?php

namespace MainBundle\Repository;

/**
 * WebsiteVilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteVilleRepository extends \Doctrine\ORM\EntityRepository
{
}
