<?php

namespace MainBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteImageRepository extends \Doctrine\ORM\EntityRepository
{
}
