

main_homepage:
    path:     accueil
    defaults: { _controller: MainBundle:Front:index }

main_tmp:
    path:     /accueilTmp
    defaults: { _controller: MainBundle:Front:indexTmp }

login:
    path:     /login
    defaults: { _controller: MainBundle:Front:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

login_tmp:  
    path:  /authentificationTmp
    defaults: {_controller:MainBundle:Front:loginTmp}

menu_association_presentation:
    path:     presentation
    defaults: { _controller: MainBundle:Front:presentation }

menu_association_adhesion:
    path:     /adhesion
    defaults: { _controller: MainBundle:Front:adhesion }

menu_actualite:
    path:     /actualite/{page}
    defaults: { _controller: MainBundle:Actualite:getAll, page:1 }

detail_actu:
    path: /detail_actu/{id}
    defaults: { _controller:MainBundle:Actualite:getById }

menu_rapport:
    path:     /rapport/{page}
    defaults: { _controller: MainBundle:Rapport:get , page:1}
    requirements:
        page:  \d*

menu_offre:
    path:     /offre/{page}/{type}/{domaine}/{lieu}
    defaults: { _controller: MainBundle:Offre:get , page:1, type:null, domaine: null, lieu:null}
    requirements:
       page:    \d*
    
detail_offre:
    path:     /detail_offre/{id}
    defaults: { _controller: MainBundle:Offre:getById}
    requirements:
        page:  \d+

menu_forum:
    path:     /forum/{page}
    defaults: { _controller: MainBundle:Forum:getByPage,page:1 }

commentaire:
    path:     /detail_forum/{id}
    defaults: { _controller: MainBundle:Forum:getByIdForum}


ajout_commentaire:
    path:     /ajoutCommentaire
    defaults: { _controller: MainBundle:Forum:ajoutCommentaire}

menu_chat:
    path:     /chat
    defaults: { _controller: MainBundle:Chat:chat }

menu_contact:
    path:     /contact
    defaults: { _controller: MainBundle:Front:contact }


menu_connexion:
    path:     /connexion
    defaults: { _controller: MainBundle:Front:connexion }
